# Custom Hyprland ASCII Art Configuration
name=hyprland
effect=beams
exec=start-hyprland

ascii_1=
  █████████  █████   ████ █████ █████ ██████   █████ ██████████ ███████████
 ███░░░░░███░░███   ███░ ░░███ ░░███ ░░██████ ░░███ ░░███░░░░░█░█░░░███░░░█
░███    ░░░  ░███  ███    ░░███ ███   ░███░███ ░███  ░███  █ ░ ░   ░███  ░
░░█████████  ░███████      ░░█████    ░███░░███░███  ░██████       ░███
 ░░░░░░░░███ ░███░░███      ░░███     ░███ ░░██████  ░███░░█       ░███
 ███    ░███ ░███ ░░███      ░███     ░███  ░░█████  ░███ ░   █    ░███
░░█████████  █████ ░░████    █████    █████  ░░█████ ██████████    █████
 ░░░░░░░░░  ░░░░░   ░░░░    ░░░░░    ░░░░░    ░░░░░ ░░░░░░░░░░    ░░░░░
